ATIRA_URL = 'https://atira.com/locations/'
ROOT_DIRECTORY = 'appartments'
USERAGENT_FILENAME = 'user_agents.txt'
EXCEPTION_RANDOM_GENERATE = 'Exception in random_ua'
APPARTMENTS_OUTPUT_FILE = 'appartments.csv'